name: Development CI/CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DEV_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_HOST }} \
          "echo Connected Successfully"


      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_HOST }} "
          cd /home/annu_singh/app &&
          git checkout dev &&
          git pull origin dev &&
          npm install &&
          sudo systemctl restart backend &&
          sudo systemctl status backend --no-pager
          "
