name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:

  build-deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}


    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2


    - name: Configure Docker Authentication
      run: |
        gcloud auth configure-docker


    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.PROJECT_ID }}/registration-app:dev .


    - name: Push Docker Image
      run: |
        docker push gcr.io/${{ secrets.PROJECT_ID }}/registration-app:dev


    - name: Deploy
      run: |
        echo "Deployment completed"